Step 7: Printing the number of times add is called
Results:
 Test 1, String is:empty, the result is:0
 Test 2, String is: 1, the result is:1
 Test 3, String is: 1,2, the result is:3
 Test 4, String is: 1,2,3 the result is:6
 Test 5, String is: 1,,3 the result is:4
 Test 6, String is: 1, the result is:1
 Test 7, String is: ,3 the result is:3
 Test 8, String is: 1\n2,3 the result is:6
 Test 9, String is: 1\n2,3\4 the result is:10
 Test 10, String is: 1\n2,3\n4,5,6\n7,9 the result is:37
 Test 11,String is: 10\n,3\n5,6 the result is:24
 Test 12,String is: 10\n,3\n5,\n the result is:18
 Test 13,String is: //;\n1;2 the result is:3
 Test 14,String is: //:\n1:2:4:5\n6 the result is:18
 Test 15,String is: //;\n1;2;4;5\n6;7;8;0\n9 the result is:42
 Test 16,String is: //;\n1;2;4;-5\n6;7;-8;0\n9 the result is:16
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-5, -8]
 Test 17, String is: 1,-2,3 the result is:2
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:24)
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-2]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:25)
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-3]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:26)
 Test 18, String is: ,-3 the result is:-3
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-1]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:27)
 Test 19, String is: -1, the result is:-1
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-1]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:28)
 Test 20, String is: -1\n2,3\4 the result is:8
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-1, -3]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:29)
 Test 21, String is: -1\n2,-3\4 the result is:2
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-1, -3, -5]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:30)
 Test 22, String is: -1\n2,-3\n4,-5,6\n7,9 the result is:19
com.java.string.calculator.exception.NegativeNumberException: negatives not allowed:[-4, -7, -9]
	at com.java.string.calculator.StringsCalculator.add(StringsCalculator.java:74)
	at com.java.assignment.tests.TestStringNumbers.main(TestStringNumbers.java:31)
 Test 23,String is: //;\n1;2;-4;5\n6;-7;8;0\n-9 the result is:2
 total number of times add called is : 23